version: '3.4'
services:
  flask:
    build: 
      context: .
      dockerfile: backend/Dockerfile
    container_name: flask_container
    tty: true
    volumes:
      - ./:/usr/src/app
    ports:
      - "5000:5000"
  vue:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    image: vue_img
    container_name: vue_container
    tty: true
    volumes:
      - ./:/usr/src/app
    ports:
      - "8080:8080"